include ../../Makefile

libs += stdio-usbacm stdio-uart0

# The GD32VF103 MicroMod comes with the biggest
# GD32VF103CB chip with 32k SRAM and 128k FLASH
# If you have made one yourself with a smaller
# chip, you can change the values below
RAM_SIZE=32*1024
FLASH_SIZE=128*1024
